variables:
  NC: '\033[0m'

  RED: '\033[00;31m'
  GREEN: '\033[00;32m'
  YELLOW: '\033[00;33m'
  BLUE: '\033[00;34m'
  PURPLE: '\033[00;35m'
  CYAN: '\033[00;36m'
  LIGHTGRAY: '\033[00;37m'

  LRED: '\033[01;31m'
  LGREEN: '\033[01;32m'
  LYELLOW: '\033[01;33m'
  LBLUE: '\033[01;34m'
  LPURPLE: '\033[01;35m'
  LCYAN: '\033[01;36m'
  WHITE: '\033[01;37m'


stages:
  - dockerize


dockerize:
  stage: dockerize
  image: kopacb/docker-bash:latest
  services:
    - docker:dind
  script:
    - DOCKERFILE="-f devops/Dockerfile"
    - IMAGE=$CI_REGISTRY_IMAGE
    - sed -i "s/APP_DEBUG=true/APP_DEBUG=false/g" .env.example
    - echo "Image is $IMAGE"
    - |
      if [[ $CI_COMMIT_REF_NAME =~ ^(dev|stage|master|main)$ ]]
      then
        IMAGE_VERSION=${CI_COMMIT_REF_NAME}-$CI_COMMIT_SHORT_SHA
      else
        IMAGE_VERSION=other-$CI_COMMIT_SHORT_SHA
      fi
    - echo "Image version is $IMAGE_VERSION"
    - docker build --no-cache -t ${IMAGE}:$IMAGE_VERSION $DOCKERFILE .
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push ${IMAGE}:$IMAGE_VERSION
    - echo "Builded and pushed ${IMAGE}:$IMAGE_VERSION"
    - echo "${IMAGE}:$IMAGE_VERSION" > IMAGE
  artifacts:
    paths:
      - IMAGE

### Trigger ###

automata_update:trigger:
  stage: deploy
  image: kopacb/basic-tools:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
#    - if: $CI_PROJECT_NAME == "manager" && $CI_COMMIT_REF_NAME == "dev" && $CI_COMMIT_MESSAGE =~ /^Merge branch.*/
#      allow_failure: true
#      when: manual
    - if: $CI_COMMIT_REF_NAME =~ /^(dev|stage|main|master)$/
    - when: never
  variables:
    PRODUCT: "youamm"
  script:
    # Variables #
    - |
      IMAGE=$(cat IMAGE | cut -d : -f 1)
      VERSION=$(cat IMAGE | cut -d : -f 2)
    # Triggering #
    - echo "Sending request to trigger pipeline for update stand, url for pipeline:"
    - |
      curl -s -X POST -F token="$AUTOMATA_UPDATE_TOKEN" -F ref=trigger \
        --form "variables[PRODUCT]=$PRODUCT" \
        --form "variables[BRANCH]=$CI_COMMIT_REF_NAME" \
        --form "variables[IMG]=$IMAGE:$VERSION" \
        $AUTOMATA_TRIGGER_URL | jq '.web_url'
